---

- name: install nginx
  include_tasks: install.yaml

- name: config nginx
  include_tasks: config.yaml

- name : start nginx
  service:
    name: nginx
    state: started
  become: true

# - name: start nginx
#   block:
#     - include_tasks: start.yaml
#   notify: Reload nginx
