#Docker section
user:
  name: ec2-user
  home: /home/ec2-user 
  project: gutenify-lynx
docker:
  container_name: portfolio
  image: lidobel3/portfolio
  deploy_portfolio: true

#Git section
git:
  key_file: /home/vagrant/.ssh/id_rsa
  repo_url: 'git@github.com:lidobel3/portfolio_ssl.git' 
  dest: /home/ec2-user/gutenify-lynx/
  version: main 