---

- name: "Verifying docker state"
  include_tasks: prerequisite.yaml

- name: "Installing container portfolio"
  include_tasks: config.yaml

- name: "Installing container portfolio"
  include_tasks: deploy.yaml