---

- name: "Verifying docker state"
  include_tasks: prerequisite.yaml

- name: "Set up the container extra dependencies"
  include_tasks: config.yaml
  #when: docker.deploy_portfolio | default(false)

- name: "Installing container portfolio"
  include_tasks: deploy.yaml
  #when: docker.deploy_portfolio_on | default(false)