---

- name: Vérifier si Docker est installé
  command: docker --version
  register: docker_check
  ignore_errors: true

- name: Installer Docker si non présent
  apt:
    name: docker.io
    state: absent
    update_cache: yes
  when: docker_check.failed
  become: true 
  become_user: vagrant

- name: Démarrer et activer le service Docker
  systemd:
    name: docker
    state: started
    enabled: yes
  when: docker_check.failed
  become: true 
