$ANSIBLE_VAULT;1.1;AES256
36373937376131633432663166333762386434383637343863343032396133363538653866366638
6530373761373265643164376430323365653765313362630a643261303066386437623632393532
61383362636165386634373630633131623265356534643335623831333737363433396638316635
6432623666326437380a633830396636356531383534306334636164616164663263356232373430
32613166643033646262313834316630393937353662366664633437396230663964356161356236
35643365313130633336633466346635656562623865306534363763313262386463346336343330
623533616230396531643638626534383565