tomcat_version : 9

#Docker section

user:
  name: vagrant
  home: /home/vagrant 
  project: gutenify-lynx
docker:
  container_name: mon_portfolio
  image: lidobel3/portfolio
  deploy_portfolio: true

#Git section
git:
  key_file: /home/{{user.name}}/.ssh/id_rsa
  repo_url: 'git@github.com:lidobel3/portfolio_ssl.git' 
  dest: /home/{{user.name}}/{{user.project}}/
  version: main 
  # token: {{ ANSIBLE_VAULT.git_token  }}   }}