$ANSIBLE_VAULT;1.1;AES256
39343135383236346137313564616232626339613130363036376236303831623636366136653038
3530363765343438386561323433343364353530373465390a613836616339616637383531616335
64306466336166643966633165643739363664313239653033393161376636323661636163626535
3463393738333637640a306265366233303730373236336430653863663938653532353462333765
36346238323861363234643537306332376463373230383032313633333336303435336135376338
37343062303330626562333565383063383466623763623963333064353139316237336237653937
63613733343137633738643962366239363063383062373565386539353637396563373861393435
38373231313630343366343237343838653034643237353363303165633430636139343664373064
63313665346435353266666230316434346234653930616338616565633033353133373762353533
65373338613266653733623264363366336263353662323033326633303931313434643833303331
38663333303634326333383462396134346164653863643661643566633165643835393634613163
64633764313032636434383561656339303332376562306466373636663834316161663639306132
35313338623764633733643131376136366263353538623963386534316437616232363835363132
64316264393738376135306130333164333639383435343037646365343766656564363339303235
65313732363135306336336432333564353235323230396436613030323863366337303166626331
31313135383437613964303865303539306635363635343130636261636439346434386165326337
65616333343135373064313331623832353831306536666433656161306437643861373864666463
63636265613262643938616661333633353431363937313236333066323239323037366665666135
36396630663130663732343562376263373533393166333161633435623230333730356565633238
30653661376539316362386537383466383930646134306561633338346435363431633332663062
34646263633832666438303234636531373537653937653063643264623836303730373163643961
30376461383332366232323263313063646637343831333833643864343036313065386437343735
30646530343638353931656134303230616365616462353432323565633835616431643939363061
65663034666333316165653961633766373830323138333064646363346333396639383364393463
38626430333039626163313339623063383436623539363634633435306332373864633135376538
6237313233356336643238393833326637373638636132323734