$ANSIBLE_VAULT;1.1;AES256
66343764393362643034643366613833626137353035336339343432353866366430326566393631
3362306335353966383765363133636632343131636339620a623139343234396535636262313362
64363966353531323931663135373539633234393065356233613262613132326235383564363761
6362383864376334650a386566303836653032326465363533623332363834316662343266626335
33343165383661666334636666646137656361633136383966316238396362316536373031663536
61373839643765316338663734316665343263386134613430383833326138613139363834313434
61336439333734326637343430393437653365393836396565333066613937333965656231643931
37303664643463363633623637643036643331366561393734663435356362613031633263303232
37346565656464353434366663636337343063366333623763666665303033653932666437623730
34633930336161643763396566353031346163333666383737393933646437326631346436646363
34636634393834363336626561643362363135373436363737633930363232306630613864333936
38623236313236376332343065663230613331623236643864616438633033343632386632613162
32623431336463333666396130373837353832613564356339663930643935356366326366643364
66643765326439323332623535663733326233323832333734623531366261353962663231643632
31346130333761616138343862393737323063636263346339653532353162363730313662613530
31633733613733663463663463343836303632306435626565393337303361393734663935383532
62373663393932346439356661653935613136316162303733666666643262326566623462323930
38623261326563333436656636613036633463656266326161626464336562356666386437643838
65343261626232313438363262656535303661306233383336366330386237336231346430333263
65326661646238636561353232343037666662313033363432396235306238343239363661313437
30346537643532623532646638653264383263326366633066333735626338313431656131623764
37393837636463343766623537303333366532643034363966363364653635653235623465636437
63383237306461326531346237616130303233666339353233356234626261653365326632343239
38643334303736393964626431326438346534363166313362636337356137343962633965663532
35383733323165313836306261323566333132653332373837376235343462613761