tomcat_version : 9

#Docker section

user:
  name: lidobel
  home: /home/lidobel 
docker:
  container_name: mon_portfolio
  image: lidobel3/portfolio
  deploy_portfolio: true

#Git section
git:
  key_file: /home/vagrant/.ssh/id_rsa
  repo_url: 'git@github.com:lidobel3/portfolio_ssl.git' 
  dest: /home/vagrant/portfolio_ssl/
  version: main 